"""Atomic incremental coverage: code derives material support from three atoms."""
from active_policy_v10 import PROMPTS, STATE_COMBINED_PROMPT


DELTA_COVERAGE_PROMPT = '''Return JSON only. prior_coverage is an immutable verified state; never regrade retained evidence. For EACH frozen requirement judge new_evidence independently of the reading order or prior score. Output exactly {"coverage":[{"id":"frozen requirement ID","any_requested_option_or_member_present":false,"requested_outcome_support":false,"population_applicable":false,"combined_requirement_complete":false,"contradiction":false,"basis_new_evidence_ids":[],"reason":"brief"}]}. Include exactly one row per requirement with exactly those eight fields. All five decision fields must be booleans, never null. Never output new_material_support, status, grade or verdict: code derives material support as the conjunction of the first three atoms.
any_requested_option_or_member_present: does NEW evidence concern ANY requested option/class/member? One option is sufficient. Absence of the other arm NEVER makes this atom false. A within-class or add-on comparison still concerns requested members.
requested_outcome_support: does NEW evidence report a concrete result for an outcome/fact requested by THIS requirement? Evaluate this separately from the comparator atom. A design-only paper or a baseline characteristic is not an outcome effect. Do not substitute a surrogate for a specifically requested clinical endpoint; a surrogate can count only when the requirement includes it. Do not invent absent safety outcomes.
population_applicable: is the NEW study population the requested or materially applicable population? Missing the other treatment arm does not change population applicability.
An applicable MRA study reporting a requested heart-failure, renal, or hyperkalemia outcome has the first three atoms true, even without an SGLT2 inhibitor arm. Such one-sided evidence remains incomplete. Conversely, presence of a requested drug alone is not sufficient without a requested outcome result.
combined_requirement_complete: retained support plus NEW evidence supplies the full requested comparison and all material scope conditions. True requires all first three atoms true. Within-class and add-on designs alone cannot establish a missing between-class comparison; do not infer that estimate. Do not upgrade just because every drug name appears in the combined sources.
contradiction: NEW evidence materially conflicts with retained support, not merely incomplete/irrelevant evidence. Use only new_evidence source_id values in basis_new_evidence_ids. Nonempty IDs are required when all first three atoms are true or contradiction=true; otherwise IDs must be empty. Every chosen ID must actually support this row, not just match a drug mention. Keep reason brief and separate factual support from missing scope.\n'''
